image: php:7.3

pipelines:
  default:
    - parallel:
        - step:
            name: Test
            script:
              - apt-get update && apt-get install -qy git curl libzip-dev zip
              - yes
              - docker-php-ext-install zip
              - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
              - composer install
              - ./vendor/bin/phpunit test
            caches:
              - composer