image: php:7.3

pipelines:
  default:
    - parallel:
        - step:
            name: Test
            script:
              - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
              - composer install
              - ./vendor/bin/phpunit test
            caches:
              - composer