image: php:7.4

pipelines:
  default:
    - parallel:
        - step:
            name: Test
            script:
              - apt-get update && apt-get install -qy git curl libzip-dev zip
              - docker-php-ext-install zip
              - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
              - composer install --ignore-platform-reqs
              - ./vendor/bin/phpunit tests
            caches:
              - composer